In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as pp

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [5]:
a.dtype

dtype('int64')

In [10]:
a = np.array([1,2,3,4,5], dtype=np.float64)
a

array([1., 2., 3., 4., 5.])

In [13]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [18]:
b = np.array([[1,2,3,4,5], [6,7,8,9,10]], dtype=np.float64)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [19]:
b.dtype

dtype('float64')

In [20]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.empty((4,4),'d')

array([[4.67567065e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [24]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [25]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [26]:
np.random.standard_normal((2,4))

array([[ 1.40775379, -0.22873517, -0.32077608, -1.29681433],
       [-2.05124782, -0.25557778, -1.03387303,  0.14985892]])

In [28]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

np.vstack([a,b])

array([[-1.44982244,  1.98916301, -2.26293603],
       [ 0.6376486 , -0.10634489,  0.77897396],
       [ 1.41950159, -0.41290469,  0.98067363],
       [-0.16284612, -1.2899107 ,  1.85190304]])

In [29]:
np.hstack([a,b])

array([[-1.44982244,  1.98916301, -2.26293603,  1.41950159, -0.41290469,
         0.98067363],
       [ 0.6376486 , -0.10634489,  0.77897396, -0.16284612, -1.2899107 ,
         1.85190304]])

In [31]:
a.transpose()

array([[-1.44982244,  0.6376486 ],
       [ 1.98916301, -0.10634489],
       [-2.26293603,  0.77897396]])

In [32]:
np.save('example.npy', a)

In [35]:
a1 = np.load('example.npy')

In [37]:
a1

array([[-1.44982244,  1.98916301, -2.26293603],
       [ 0.6376486 , -0.10634489,  0.77897396]])