In [1]:
import numpy as np

In [2]:
v = np.linspace(0, 10, 5)

In [3]:
v[0]

0.0

In [4]:
v[1]

2.5

In [5]:
v[-1]

10.0

In [6]:
v[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

In [8]:
vv = np.random.random((5,4))

In [9]:
vv

array([[0.19521738, 0.93538117, 0.65617505, 0.53545784],
       [0.41346697, 0.43653725, 0.65251817, 0.32488858],
       [0.46086297, 0.12198395, 0.61485492, 0.59085779],
       [0.51849204, 0.45043723, 0.7350595 , 0.46406692],
       [0.87619825, 0.80859801, 0.9840576 , 0.47466332]])

In [10]:
vv[0,0]

0.19521737962922492

In [11]:
vv[4,3]

0.47466331725227917

In [12]:
ll = [[1,2,3], [4,5,6], [7,8,9]]

In [13]:
ll

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
ll[0][0]

1

In [15]:
ll[0][1]

2

In [16]:
ll[1][0]

4

In [17]:
ll[1][2]

6

In [18]:
v[2:4]

array([5. , 7.5])

In [19]:
ll[0:1]

[[1, 2, 3]]

In [20]:
ll[1:2]

[[4, 5, 6]]

In [21]:
ll[2:3]

[[7, 8, 9]]

In [22]:
vv[2:5, 1]

array([0.12198395, 0.45043723, 0.80859801])

In [23]:
vv[2:5]

array([[0.46086297, 0.12198395, 0.61485492, 0.59085779],
       [0.51849204, 0.45043723, 0.7350595 , 0.46406692],
       [0.87619825, 0.80859801, 0.9840576 , 0.47466332]])

In [24]:
vv[2:5, 1:2]

array([[0.12198395],
       [0.45043723],
       [0.80859801]])

In [25]:
vv[2:-1,:]

array([[0.46086297, 0.12198395, 0.61485492, 0.59085779],
       [0.51849204, 0.45043723, 0.7350595 , 0.46406692]])

In [26]:
vv[:,::2]

array([[0.19521738, 0.65617505],
       [0.41346697, 0.65251817],
       [0.46086297, 0.61485492],
       [0.51849204, 0.7350595 ],
       [0.87619825, 0.9840576 ]])

In [27]:
v2 = v[2:4]

In [28]:
v2[0] = 0

In [30]:
v

array([ 0. ,  2.5,  0. ,  7.5, 10. ])

In [31]:
v3 = v[2:4].copy()

In [32]:
v3[0] = 1

In [33]:
v3

array([1. , 7.5])

In [34]:
v[1,2,3]

IndexError: too many indices for array

In [35]:
v[[1,2,3]]

array([2.5, 0. , 7.5])

In [37]:
bool_index = v > 0

In [38]:
v[bool_index]

array([ 2.5,  7.5, 10. ])

In [39]:
vv[vv > 0.5] = vv[vv > 0.5]*2

In [40]:
vv

array([[0.19521738, 1.87076235, 1.31235011, 1.07091569],
       [0.41346697, 0.43653725, 1.30503634, 0.32488858],
       [0.46086297, 0.12198395, 1.22970984, 1.18171559],
       [1.03698408, 0.45043723, 1.47011899, 0.46406692],
       [1.7523965 , 1.61719603, 1.96811521, 0.47466332]])